from __future__ import annotations

from pathlib import Path
from datetime import datetime
from typing import Protocol

from thermal_app.application.dto import EncodedPayload, RenderedDocument
from thermal_app.domain.models import (
    IntegrationProfile,
    CustomTemplate,
    PaperProfile,
    Preset,
    PrinterProfile,
    PrintJob,
    TodoistCacheEntry,
)


class PrinterProfileRepository(Protocol):
    def save(self, profile: PrinterProfile) -> None: ...
    def get(self, profile_id: str) -> PrinterProfile | None: ...
    def list_all(self) -> list[PrinterProfile]: ...


class PaperProfileRepository(Protocol):
    def save(self, profile: PaperProfile) -> None: ...
    def get(self, profile_id: str) -> PaperProfile | None: ...
    def list_all(self) -> list[PaperProfile]: ...
    def delete(self, profile_id: str) -> bool: ...


class PrintJobRepository(Protocol):
    def save(self, job: PrintJob) -> None: ...
    def get(self, job_id: str) -> PrintJob | None: ...
    def list_recent(self, limit: int = 100) -> list[PrintJob]: ...
    def list_filtered(
        self,
        start_at: datetime | None = None,
        end_at: datetime | None = None,
        statuses: tuple[str, ...] | None = None,
        limit: int = 100,
    ) -> list[PrintJob]: ...
    def delete(self, job_id: str) -> bool: ...
    def delete_many(self, job_ids: list[str]) -> int: ...


class IntegrationProfileRepository(Protocol):
    def save(self, profile: IntegrationProfile) -> None: ...
    def get(self, profile_id: str) -> IntegrationProfile | None: ...


class TodoistCacheRepository(Protocol):
    def save(self, entry: TodoistCacheEntry) -> None: ...
    def get(self, cache_key: str) -> TodoistCacheEntry | None: ...


class PresetRepository(Protocol):
    def save(self, preset: Preset) -> None: ...
    def get(self, preset_id: str) -> Preset | None: ...
    def list_all(self) -> list[Preset]: ...
    def delete(self, preset_id: str) -> bool: ...


class CustomTemplateRepository(Protocol):
    def save(self, template: CustomTemplate) -> None: ...
    def get(self, template_id: str) -> CustomTemplate | None: ...
    def list_all(self) -> list[CustomTemplate]: ...
    def delete(self, template_id: str) -> bool: ...


class SettingsRepository(Protocol):
    def set(self, key: str, value: str) -> None: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...


class CredentialStore(Protocol):
    def save(self, reference: str, secret: str) -> None: ...
    def get(self, reference: str) -> str | None: ...
    def delete(self, reference: str) -> None: ...


class ArtifactStore(Protocol):
    def save_bitmap(self, job_id: str, document: RenderedDocument) -> Path: ...
    def save_preview(self, job_id: str, document: RenderedDocument) -> Path: ...
    def save_encoded(self, job_id: str, payload: EncodedPayload) -> Path: ...
    def read_encoded(self, path: Path) -> bytes: ...
    def delete_paths(self, paths: list[Path]) -> int: ...
